services:
  - type: web
    name: iris-bank-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://iris-bank-frontend-4atk0grwp-sanjus-projects-48f9be41.vercel.app 
